# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  go: '1.21'
  tests: true
  build-tags:
    - integration
    - tpm_integration

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

  disable:
    - depguard  # We manage deps via go.mod
    - funlen    # Some functions are necessarily long
    - lll       # Line length handled by gofmt
    - wsl       # Whitespace style is subjective

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io.Copy
      - io.WriteString
      - (*bytes.Buffer).WriteString

  govet:
    enable-all: true
    disable:
      - shadow  # Too many false positives

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - ifElseChain
      - whyNoLint

  gofmt:
    simplify: true

  goimports:
    local-prefixes: witnessd

  gosec:
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
      - G304  # File path from variable (intentional in our case)

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  stylecheck:
    go: "1.21"
    checks:
      - all
      - -ST1000  # Package comments
      - -ST1003  # Underscores in names

issues:
  exclude-rules:
    # Test files can have longer functions
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec

    # Generated files
    - path: _gen\.go
      linters:
        - all

    # Main packages
    - path: cmd/
      linters:
        - gochecknoinits

  max-issues-per-linter: 50
  max-same-issues: 3
