name: Security Vulnerability
description: Report a security issue (for non-sensitive issues only)
title: "[Security]: "
labels: ["security", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Important Security Notice

        **For sensitive security vulnerabilities, please DO NOT use this form.**

        Instead, report via email to: admin@writerslogic.com

        This form is only for non-sensitive security-related issues such as:
        - Documentation improvements for security features
        - General security hardening suggestions
        - Questions about the threat model

  - type: checkboxes
    id: sensitive
    attributes:
      label: Sensitivity Check
      options:
        - label: This issue does NOT contain sensitive vulnerability details
          required: true
        - label: Disclosing this publicly will NOT put users at risk
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security-related issue
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Documentation improvement
        - Hardening suggestion
        - Threat model question
        - Dependency concern
        - Other
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How could this be improved?
