// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1636891669;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'witnessd_core',
        ioDirectory: '../rust/witnessd-core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateBridgeAccessibilityTrusted();

  Future<FrbForensicReport> crateBridgeAnalyzeDocument({required String path});

  Future<FrbVdfParams> crateBridgeCalibrateVdf();

  Future<FrbHardwareStatus> crateBridgeCheckHardwareStatus();

  Future<FrbCheckpointInfo> crateBridgeCommitDocument({
    required String path,
    String? message,
  });

  Future<FrbPresenceStatus> crateBridgeEndPresenceSession();

  Future<FrbEngineStatus?> crateBridgeEngineStatus();

  Future<FrbExportResult> crateBridgeExportEvidence({
    required String path,
    required String title,
    required String tier,
  });

  Future<String> crateBridgeGenerateMnemonic();

  Future<double> crateBridgeGetCadenceScore({required String path});

  Future<FrbAppConfig> crateBridgeGetConfig();

  Future<List<FrbCheckpointInfo>> crateBridgeGetDocumentLog({
    required String path,
  });

  Future<FrbEngineConfig> crateBridgeGetEngineConfig();

  Future<double> crateBridgeGetForensicScore({required String filePath});

  Future<String?> crateBridgeGetIdentityFingerprint();

  Future<FrbChallengeInfo?> crateBridgeGetPendingChallenge();

  Future<String> crateBridgeGetPlatform();

  Future<FrbPresenceStatus> crateBridgeGetPresenceStatus();

  Future<FrbTrackingStatistics> crateBridgeGetTrackingStatistics();

  Future<FrbTrackingStatus> crateBridgeGetTrackingStatus();

  Future<FrbVdfParams> crateBridgeGetVdfParams();

  Future<String> crateBridgeGetVersion();

  Future<String> crateBridgeInitWitnessd({String? dataDir, String? mnemonic});

  Future<bool> crateBridgeInputMonitoringTrusted();

  Future<bool> crateBridgeIsInitialized();

  Future<bool> crateBridgeIsSupportedPlatform();

  Future<void> crateBridgeOpenAccessibilitySettings();

  Future<void> crateBridgeOpenInputMonitoringSettings();

  Future<(int, bool)> crateBridgeRecordKeystroke();

  Future<List<FrbReportFile>> crateBridgeReportFiles();

  Future<bool> crateBridgeRequestAccessibilityPermissions();

  Future<bool> crateBridgeRequestInputMonitoringPermissions();

  Future<void> crateBridgeSetConfig({required FrbAppConfig config});

  Future<void> crateBridgeSetEngineConfig({required FrbEngineConfig config});

  Future<String> crateBridgeSetupIdentity({required String phrase});

  Future<FrbEngineStatus> crateBridgeStartEngine();

  Future<String> crateBridgeStartPresenceSession();

  Future<void> crateBridgeStartTracking({required String path});

  Future<void> crateBridgeStopEngine();

  Future<FrbTrackingStatistics> crateBridgeStopTracking();

  Future<bool> crateBridgeSubmitChallengeResponse({required String response});

  Future<FrbVerificationResult> crateBridgeVerifyDocument({
    required String path,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateBridgeAccessibilityTrusted() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeAccessibilityTrustedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeAccessibilityTrustedConstMeta =>
      const TaskConstMeta(debugName: "accessibility_trusted", argNames: []);

  @override
  Future<FrbForensicReport> crateBridgeAnalyzeDocument({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_forensic_report,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeAnalyzeDocumentConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeAnalyzeDocumentConstMeta =>
      const TaskConstMeta(debugName: "analyze_document", argNames: ["path"]);

  @override
  Future<FrbVdfParams> crateBridgeCalibrateVdf() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_vdf_params,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeCalibrateVdfConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeCalibrateVdfConstMeta =>
      const TaskConstMeta(debugName: "calibrate_vdf", argNames: []);

  @override
  Future<FrbHardwareStatus> crateBridgeCheckHardwareStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_hardware_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeCheckHardwareStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeCheckHardwareStatusConstMeta =>
      const TaskConstMeta(debugName: "check_hardware_status", argNames: []);

  @override
  Future<FrbCheckpointInfo> crateBridgeCommitDocument({
    required String path,
    String? message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_opt_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_checkpoint_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeCommitDocumentConstMeta,
        argValues: [path, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeCommitDocumentConstMeta => const TaskConstMeta(
    debugName: "commit_document",
    argNames: ["path", "message"],
  );

  @override
  Future<FrbPresenceStatus> crateBridgeEndPresenceSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_presence_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeEndPresenceSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeEndPresenceSessionConstMeta =>
      const TaskConstMeta(debugName: "end_presence_session", argNames: []);

  @override
  Future<FrbEngineStatus?> crateBridgeEngineStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_frb_engine_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeEngineStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeEngineStatusConstMeta =>
      const TaskConstMeta(debugName: "engine_status", argNames: []);

  @override
  Future<FrbExportResult> crateBridgeExportEvidence({
    required String path,
    required String title,
    required String tier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(tier, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_export_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeExportEvidenceConstMeta,
        argValues: [path, title, tier],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeExportEvidenceConstMeta => const TaskConstMeta(
    debugName: "export_evidence",
    argNames: ["path", "title", "tier"],
  );

  @override
  Future<String> crateBridgeGenerateMnemonic() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeGenerateMnemonicConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGenerateMnemonicConstMeta =>
      const TaskConstMeta(debugName: "generate_mnemonic", argNames: []);

  @override
  Future<double> crateBridgeGetCadenceScore({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeGetCadenceScoreConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetCadenceScoreConstMeta =>
      const TaskConstMeta(debugName: "get_cadence_score", argNames: ["path"]);

  @override
  Future<FrbAppConfig> crateBridgeGetConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_app_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeGetConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetConfigConstMeta =>
      const TaskConstMeta(debugName: "get_config", argNames: []);

  @override
  Future<List<FrbCheckpointInfo>> crateBridgeGetDocumentLog({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_frb_checkpoint_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeGetDocumentLogConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetDocumentLogConstMeta =>
      const TaskConstMeta(debugName: "get_document_log", argNames: ["path"]);

  @override
  Future<FrbEngineConfig> crateBridgeGetEngineConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_engine_config,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeGetEngineConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetEngineConfigConstMeta =>
      const TaskConstMeta(debugName: "get_engine_config", argNames: []);

  @override
  Future<double> crateBridgeGetForensicScore({required String filePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeGetForensicScoreConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetForensicScoreConstMeta =>
      const TaskConstMeta(
        debugName: "get_forensic_score",
        argNames: ["filePath"],
      );

  @override
  Future<String?> crateBridgeGetIdentityFingerprint() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeGetIdentityFingerprintConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetIdentityFingerprintConstMeta =>
      const TaskConstMeta(debugName: "get_identity_fingerprint", argNames: []);

  @override
  Future<FrbChallengeInfo?> crateBridgeGetPendingChallenge() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_frb_challenge_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeGetPendingChallengeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetPendingChallengeConstMeta =>
      const TaskConstMeta(debugName: "get_pending_challenge", argNames: []);

  @override
  Future<String> crateBridgeGetPlatform() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeGetPlatformConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetPlatformConstMeta =>
      const TaskConstMeta(debugName: "get_platform", argNames: []);

  @override
  Future<FrbPresenceStatus> crateBridgeGetPresenceStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_presence_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeGetPresenceStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetPresenceStatusConstMeta =>
      const TaskConstMeta(debugName: "get_presence_status", argNames: []);

  @override
  Future<FrbTrackingStatistics> crateBridgeGetTrackingStatistics() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_tracking_statistics,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeGetTrackingStatisticsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetTrackingStatisticsConstMeta =>
      const TaskConstMeta(debugName: "get_tracking_statistics", argNames: []);

  @override
  Future<FrbTrackingStatus> crateBridgeGetTrackingStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_tracking_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeGetTrackingStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetTrackingStatusConstMeta =>
      const TaskConstMeta(debugName: "get_tracking_status", argNames: []);

  @override
  Future<FrbVdfParams> crateBridgeGetVdfParams() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_vdf_params,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeGetVdfParamsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetVdfParamsConstMeta =>
      const TaskConstMeta(debugName: "get_vdf_params", argNames: []);

  @override
  Future<String> crateBridgeGetVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeGetVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeGetVersionConstMeta =>
      const TaskConstMeta(debugName: "get_version", argNames: []);

  @override
  Future<String> crateBridgeInitWitnessd({String? dataDir, String? mnemonic}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(dataDir, serializer);
          sse_encode_opt_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeInitWitnessdConstMeta,
        argValues: [dataDir, mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeInitWitnessdConstMeta => const TaskConstMeta(
    debugName: "init_witnessd",
    argNames: ["dataDir", "mnemonic"],
  );

  @override
  Future<bool> crateBridgeInputMonitoringTrusted() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeInputMonitoringTrustedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeInputMonitoringTrustedConstMeta =>
      const TaskConstMeta(debugName: "input_monitoring_trusted", argNames: []);

  @override
  Future<bool> crateBridgeIsInitialized() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeIsInitializedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeIsInitializedConstMeta =>
      const TaskConstMeta(debugName: "is_initialized", argNames: []);

  @override
  Future<bool> crateBridgeIsSupportedPlatform() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeIsSupportedPlatformConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeIsSupportedPlatformConstMeta =>
      const TaskConstMeta(debugName: "is_supported_platform", argNames: []);

  @override
  Future<void> crateBridgeOpenAccessibilitySettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeOpenAccessibilitySettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeOpenAccessibilitySettingsConstMeta =>
      const TaskConstMeta(
        debugName: "open_accessibility_settings",
        argNames: [],
      );

  @override
  Future<void> crateBridgeOpenInputMonitoringSettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeOpenInputMonitoringSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeOpenInputMonitoringSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "open_input_monitoring_settings",
        argNames: [],
      );

  @override
  Future<(int, bool)> crateBridgeRecordKeystroke() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_u_32_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeRecordKeystrokeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeRecordKeystrokeConstMeta =>
      const TaskConstMeta(debugName: "record_keystroke", argNames: []);

  @override
  Future<List<FrbReportFile>> crateBridgeReportFiles() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_frb_report_file,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeReportFilesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeReportFilesConstMeta =>
      const TaskConstMeta(debugName: "report_files", argNames: []);

  @override
  Future<bool> crateBridgeRequestAccessibilityPermissions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeRequestAccessibilityPermissionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeRequestAccessibilityPermissionsConstMeta =>
      const TaskConstMeta(
        debugName: "request_accessibility_permissions",
        argNames: [],
      );

  @override
  Future<bool> crateBridgeRequestInputMonitoringPermissions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateBridgeRequestInputMonitoringPermissionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeRequestInputMonitoringPermissionsConstMeta =>
      const TaskConstMeta(
        debugName: "request_input_monitoring_permissions",
        argNames: [],
      );

  @override
  Future<void> crateBridgeSetConfig({required FrbAppConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_frb_app_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeSetConfigConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeSetConfigConstMeta =>
      const TaskConstMeta(debugName: "set_config", argNames: ["config"]);

  @override
  Future<void> crateBridgeSetEngineConfig({required FrbEngineConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_frb_engine_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeSetEngineConfigConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeSetEngineConfigConstMeta =>
      const TaskConstMeta(debugName: "set_engine_config", argNames: ["config"]);

  @override
  Future<String> crateBridgeSetupIdentity({required String phrase}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeSetupIdentityConstMeta,
        argValues: [phrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeSetupIdentityConstMeta =>
      const TaskConstMeta(debugName: "setup_identity", argNames: ["phrase"]);

  @override
  Future<FrbEngineStatus> crateBridgeStartEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_engine_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeStartEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeStartEngineConstMeta =>
      const TaskConstMeta(debugName: "start_engine", argNames: []);

  @override
  Future<String> crateBridgeStartPresenceSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeStartPresenceSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeStartPresenceSessionConstMeta =>
      const TaskConstMeta(debugName: "start_presence_session", argNames: []);

  @override
  Future<void> crateBridgeStartTracking({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeStartTrackingConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeStartTrackingConstMeta =>
      const TaskConstMeta(debugName: "start_tracking", argNames: ["path"]);

  @override
  Future<void> crateBridgeStopEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeStopEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeStopEngineConstMeta =>
      const TaskConstMeta(debugName: "stop_engine", argNames: []);

  @override
  Future<FrbTrackingStatistics> crateBridgeStopTracking() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_tracking_statistics,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeStopTrackingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeStopTrackingConstMeta =>
      const TaskConstMeta(debugName: "stop_tracking", argNames: []);

  @override
  Future<bool> crateBridgeSubmitChallengeResponse({required String response}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(response, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeSubmitChallengeResponseConstMeta,
        argValues: [response],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeSubmitChallengeResponseConstMeta =>
      const TaskConstMeta(
        debugName: "submit_challenge_response",
        argNames: ["response"],
      );

  @override
  Future<FrbVerificationResult> crateBridgeVerifyDocument({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frb_verification_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateBridgeVerifyDocumentConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateBridgeVerifyDocumentConstMeta =>
      const TaskConstMeta(debugName: "verify_document", argNames: ["path"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FrbAppConfig dco_decode_box_autoadd_frb_app_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_frb_app_config(raw);
  }

  @protected
  FrbChallengeInfo dco_decode_box_autoadd_frb_challenge_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_frb_challenge_info(raw);
  }

  @protected
  FrbEngineConfig dco_decode_box_autoadd_frb_engine_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_frb_engine_config(raw);
  }

  @protected
  FrbEngineStatus dco_decode_box_autoadd_frb_engine_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_frb_engine_status(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FrbAppConfig dco_decode_frb_app_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FrbAppConfig(
      dataDir: dco_decode_String(arr[0]),
      watchDirs: dco_decode_list_String(arr[1]),
      retentionDays: dco_decode_u_32(arr[2]),
      presenceChallengeIntervalSecs: dco_decode_u_64(arr[3]),
      presenceResponseWindowSecs: dco_decode_u_64(arr[4]),
      vdfParams: dco_decode_frb_vdf_params(arr[5]),
    );
  }

  @protected
  FrbChallengeInfo dco_decode_frb_challenge_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FrbChallengeInfo(
      id: dco_decode_String(arr[0]),
      challengeType: dco_decode_String(arr[1]),
      prompt: dco_decode_String(arr[2]),
      issuedAt: dco_decode_String(arr[3]),
      expiresAt: dco_decode_String(arr[4]),
      windowSecs: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  FrbCheckpointInfo dco_decode_frb_checkpoint_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FrbCheckpointInfo(
      ordinal: dco_decode_u_64(arr[0]),
      timestamp: dco_decode_String(arr[1]),
      contentHash: dco_decode_String(arr[2]),
      contentSize: dco_decode_i_64(arr[3]),
      message: dco_decode_opt_String(arr[4]),
      hasVdfProof: dco_decode_bool(arr[5]),
      elapsedTimeSecs: dco_decode_opt_box_autoadd_f_64(arr[6]),
    );
  }

  @protected
  FrbEngineConfig dco_decode_frb_engine_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FrbEngineConfig(
      dataDir: dco_decode_String(arr[0]),
      watchDirs: dco_decode_list_String(arr[1]),
      retentionDays: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  FrbEngineStatus dco_decode_frb_engine_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FrbEngineStatus(
      running: dco_decode_bool(arr[0]),
      accessibilityTrusted: dco_decode_bool(arr[1]),
      watchDirs: dco_decode_list_String(arr[2]),
      eventsWritten: dco_decode_u_64(arr[3]),
      jitterSamples: dco_decode_u_64(arr[4]),
      lastEventTimestampNs: dco_decode_opt_box_autoadd_i_64(arr[5]),
    );
  }

  @protected
  FrbExportResult dco_decode_frb_export_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FrbExportResult(
      success: dco_decode_bool(arr[0]),
      outputPath: dco_decode_opt_String(arr[1]),
      packetHash: dco_decode_opt_String(arr[2]),
      error: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  FrbForensicReport dco_decode_frb_forensic_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FrbForensicReport(
      confidenceScore: dco_decode_f_64(arr[0]),
      isAnomaly: dco_decode_bool(arr[1]),
      isRetypedContent: dco_decode_bool(arr[2]),
      signalCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  FrbHardwareStatus dco_decode_frb_hardware_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FrbHardwareStatus(
      enclaveActive: dco_decode_bool(arr[0]),
      tpmActive: dco_decode_bool(arr[1]),
      siliconId: dco_decode_String(arr[2]),
    );
  }

  @protected
  FrbPresenceStatus dco_decode_frb_presence_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return FrbPresenceStatus(
      sessionActive: dco_decode_bool(arr[0]),
      sessionId: dco_decode_opt_String(arr[1]),
      startedAt: dco_decode_opt_String(arr[2]),
      challengesIssued: dco_decode_i_32(arr[3]),
      challengesPassed: dco_decode_i_32(arr[4]),
      challengesFailed: dco_decode_i_32(arr[5]),
      challengesMissed: dco_decode_i_32(arr[6]),
      verificationRate: dco_decode_f_64(arr[7]),
      hasPendingChallenge: dco_decode_bool(arr[8]),
    );
  }

  @protected
  FrbReportFile dco_decode_frb_report_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FrbReportFile(
      filePath: dco_decode_String(arr[0]),
      lastEventTimestampNs: dco_decode_i_64(arr[1]),
      eventCount: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  FrbTrackingStatistics dco_decode_frb_tracking_statistics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FrbTrackingStatistics(
      totalKeystrokes: dco_decode_u_64(arr[0]),
      totalSamples: dco_decode_i_32(arr[1]),
      durationSecs: dco_decode_f_64(arr[2]),
      keystrokesPerMin: dco_decode_f_64(arr[3]),
      uniqueDocHashes: dco_decode_i_32(arr[4]),
      chainValid: dco_decode_bool(arr[5]),
    );
  }

  @protected
  FrbTrackingStatus dco_decode_frb_tracking_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FrbTrackingStatus(
      active: dco_decode_bool(arr[0]),
      sessionId: dco_decode_opt_String(arr[1]),
      documentPath: dco_decode_opt_String(arr[2]),
      startedAt: dco_decode_opt_String(arr[3]),
      keystrokeCount: dco_decode_u_64(arr[4]),
      sampleCount: dco_decode_u_32(arr[5]),
      durationSecs: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  FrbVdfParams dco_decode_frb_vdf_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FrbVdfParams(
      iterationsPerSecond: dco_decode_u_64(arr[0]),
      minIterations: dco_decode_u_64(arr[1]),
      maxIterations: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  FrbVerificationResult dco_decode_frb_verification_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FrbVerificationResult(
      valid: dco_decode_bool(arr[0]),
      checkpointCount: dco_decode_u_32(arr[1]),
      totalElapsedTimeSecs: dco_decode_f_64(arr[2]),
      firstCommit: dco_decode_opt_String(arr[3]),
      lastCommit: dco_decode_opt_String(arr[4]),
      errors: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FrbCheckpointInfo> dco_decode_list_frb_checkpoint_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_frb_checkpoint_info).toList();
  }

  @protected
  List<FrbReportFile> dco_decode_list_frb_report_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_frb_report_file).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  FrbChallengeInfo? dco_decode_opt_box_autoadd_frb_challenge_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_frb_challenge_info(raw);
  }

  @protected
  FrbEngineStatus? dco_decode_opt_box_autoadd_frb_engine_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_frb_engine_status(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  (int, bool) dco_decode_record_u_32_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_u_32(arr[0]), dco_decode_bool(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  FrbAppConfig sse_decode_box_autoadd_frb_app_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_frb_app_config(deserializer));
  }

  @protected
  FrbChallengeInfo sse_decode_box_autoadd_frb_challenge_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_frb_challenge_info(deserializer));
  }

  @protected
  FrbEngineConfig sse_decode_box_autoadd_frb_engine_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_frb_engine_config(deserializer));
  }

  @protected
  FrbEngineStatus sse_decode_box_autoadd_frb_engine_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_frb_engine_status(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FrbAppConfig sse_decode_frb_app_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dataDir = sse_decode_String(deserializer);
    var var_watchDirs = sse_decode_list_String(deserializer);
    var var_retentionDays = sse_decode_u_32(deserializer);
    var var_presenceChallengeIntervalSecs = sse_decode_u_64(deserializer);
    var var_presenceResponseWindowSecs = sse_decode_u_64(deserializer);
    var var_vdfParams = sse_decode_frb_vdf_params(deserializer);
    return FrbAppConfig(
      dataDir: var_dataDir,
      watchDirs: var_watchDirs,
      retentionDays: var_retentionDays,
      presenceChallengeIntervalSecs: var_presenceChallengeIntervalSecs,
      presenceResponseWindowSecs: var_presenceResponseWindowSecs,
      vdfParams: var_vdfParams,
    );
  }

  @protected
  FrbChallengeInfo sse_decode_frb_challenge_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_challengeType = sse_decode_String(deserializer);
    var var_prompt = sse_decode_String(deserializer);
    var var_issuedAt = sse_decode_String(deserializer);
    var var_expiresAt = sse_decode_String(deserializer);
    var var_windowSecs = sse_decode_f_64(deserializer);
    return FrbChallengeInfo(
      id: var_id,
      challengeType: var_challengeType,
      prompt: var_prompt,
      issuedAt: var_issuedAt,
      expiresAt: var_expiresAt,
      windowSecs: var_windowSecs,
    );
  }

  @protected
  FrbCheckpointInfo sse_decode_frb_checkpoint_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ordinal = sse_decode_u_64(deserializer);
    var var_timestamp = sse_decode_String(deserializer);
    var var_contentHash = sse_decode_String(deserializer);
    var var_contentSize = sse_decode_i_64(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_hasVdfProof = sse_decode_bool(deserializer);
    var var_elapsedTimeSecs = sse_decode_opt_box_autoadd_f_64(deserializer);
    return FrbCheckpointInfo(
      ordinal: var_ordinal,
      timestamp: var_timestamp,
      contentHash: var_contentHash,
      contentSize: var_contentSize,
      message: var_message,
      hasVdfProof: var_hasVdfProof,
      elapsedTimeSecs: var_elapsedTimeSecs,
    );
  }

  @protected
  FrbEngineConfig sse_decode_frb_engine_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dataDir = sse_decode_String(deserializer);
    var var_watchDirs = sse_decode_list_String(deserializer);
    var var_retentionDays = sse_decode_u_32(deserializer);
    return FrbEngineConfig(
      dataDir: var_dataDir,
      watchDirs: var_watchDirs,
      retentionDays: var_retentionDays,
    );
  }

  @protected
  FrbEngineStatus sse_decode_frb_engine_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_running = sse_decode_bool(deserializer);
    var var_accessibilityTrusted = sse_decode_bool(deserializer);
    var var_watchDirs = sse_decode_list_String(deserializer);
    var var_eventsWritten = sse_decode_u_64(deserializer);
    var var_jitterSamples = sse_decode_u_64(deserializer);
    var var_lastEventTimestampNs = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    return FrbEngineStatus(
      running: var_running,
      accessibilityTrusted: var_accessibilityTrusted,
      watchDirs: var_watchDirs,
      eventsWritten: var_eventsWritten,
      jitterSamples: var_jitterSamples,
      lastEventTimestampNs: var_lastEventTimestampNs,
    );
  }

  @protected
  FrbExportResult sse_decode_frb_export_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_outputPath = sse_decode_opt_String(deserializer);
    var var_packetHash = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return FrbExportResult(
      success: var_success,
      outputPath: var_outputPath,
      packetHash: var_packetHash,
      error: var_error,
    );
  }

  @protected
  FrbForensicReport sse_decode_frb_forensic_report(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_confidenceScore = sse_decode_f_64(deserializer);
    var var_isAnomaly = sse_decode_bool(deserializer);
    var var_isRetypedContent = sse_decode_bool(deserializer);
    var var_signalCount = sse_decode_u_32(deserializer);
    return FrbForensicReport(
      confidenceScore: var_confidenceScore,
      isAnomaly: var_isAnomaly,
      isRetypedContent: var_isRetypedContent,
      signalCount: var_signalCount,
    );
  }

  @protected
  FrbHardwareStatus sse_decode_frb_hardware_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enclaveActive = sse_decode_bool(deserializer);
    var var_tpmActive = sse_decode_bool(deserializer);
    var var_siliconId = sse_decode_String(deserializer);
    return FrbHardwareStatus(
      enclaveActive: var_enclaveActive,
      tpmActive: var_tpmActive,
      siliconId: var_siliconId,
    );
  }

  @protected
  FrbPresenceStatus sse_decode_frb_presence_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionActive = sse_decode_bool(deserializer);
    var var_sessionId = sse_decode_opt_String(deserializer);
    var var_startedAt = sse_decode_opt_String(deserializer);
    var var_challengesIssued = sse_decode_i_32(deserializer);
    var var_challengesPassed = sse_decode_i_32(deserializer);
    var var_challengesFailed = sse_decode_i_32(deserializer);
    var var_challengesMissed = sse_decode_i_32(deserializer);
    var var_verificationRate = sse_decode_f_64(deserializer);
    var var_hasPendingChallenge = sse_decode_bool(deserializer);
    return FrbPresenceStatus(
      sessionActive: var_sessionActive,
      sessionId: var_sessionId,
      startedAt: var_startedAt,
      challengesIssued: var_challengesIssued,
      challengesPassed: var_challengesPassed,
      challengesFailed: var_challengesFailed,
      challengesMissed: var_challengesMissed,
      verificationRate: var_verificationRate,
      hasPendingChallenge: var_hasPendingChallenge,
    );
  }

  @protected
  FrbReportFile sse_decode_frb_report_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filePath = sse_decode_String(deserializer);
    var var_lastEventTimestampNs = sse_decode_i_64(deserializer);
    var var_eventCount = sse_decode_u_64(deserializer);
    return FrbReportFile(
      filePath: var_filePath,
      lastEventTimestampNs: var_lastEventTimestampNs,
      eventCount: var_eventCount,
    );
  }

  @protected
  FrbTrackingStatistics sse_decode_frb_tracking_statistics(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalKeystrokes = sse_decode_u_64(deserializer);
    var var_totalSamples = sse_decode_i_32(deserializer);
    var var_durationSecs = sse_decode_f_64(deserializer);
    var var_keystrokesPerMin = sse_decode_f_64(deserializer);
    var var_uniqueDocHashes = sse_decode_i_32(deserializer);
    var var_chainValid = sse_decode_bool(deserializer);
    return FrbTrackingStatistics(
      totalKeystrokes: var_totalKeystrokes,
      totalSamples: var_totalSamples,
      durationSecs: var_durationSecs,
      keystrokesPerMin: var_keystrokesPerMin,
      uniqueDocHashes: var_uniqueDocHashes,
      chainValid: var_chainValid,
    );
  }

  @protected
  FrbTrackingStatus sse_decode_frb_tracking_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_active = sse_decode_bool(deserializer);
    var var_sessionId = sse_decode_opt_String(deserializer);
    var var_documentPath = sse_decode_opt_String(deserializer);
    var var_startedAt = sse_decode_opt_String(deserializer);
    var var_keystrokeCount = sse_decode_u_64(deserializer);
    var var_sampleCount = sse_decode_u_32(deserializer);
    var var_durationSecs = sse_decode_f_64(deserializer);
    return FrbTrackingStatus(
      active: var_active,
      sessionId: var_sessionId,
      documentPath: var_documentPath,
      startedAt: var_startedAt,
      keystrokeCount: var_keystrokeCount,
      sampleCount: var_sampleCount,
      durationSecs: var_durationSecs,
    );
  }

  @protected
  FrbVdfParams sse_decode_frb_vdf_params(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_iterationsPerSecond = sse_decode_u_64(deserializer);
    var var_minIterations = sse_decode_u_64(deserializer);
    var var_maxIterations = sse_decode_u_64(deserializer);
    return FrbVdfParams(
      iterationsPerSecond: var_iterationsPerSecond,
      minIterations: var_minIterations,
      maxIterations: var_maxIterations,
    );
  }

  @protected
  FrbVerificationResult sse_decode_frb_verification_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_valid = sse_decode_bool(deserializer);
    var var_checkpointCount = sse_decode_u_32(deserializer);
    var var_totalElapsedTimeSecs = sse_decode_f_64(deserializer);
    var var_firstCommit = sse_decode_opt_String(deserializer);
    var var_lastCommit = sse_decode_opt_String(deserializer);
    var var_errors = sse_decode_list_String(deserializer);
    return FrbVerificationResult(
      valid: var_valid,
      checkpointCount: var_checkpointCount,
      totalElapsedTimeSecs: var_totalElapsedTimeSecs,
      firstCommit: var_firstCommit,
      lastCommit: var_lastCommit,
      errors: var_errors,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FrbCheckpointInfo> sse_decode_list_frb_checkpoint_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FrbCheckpointInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_frb_checkpoint_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<FrbReportFile> sse_decode_list_frb_report_file(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FrbReportFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_frb_report_file(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FrbChallengeInfo? sse_decode_opt_box_autoadd_frb_challenge_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_frb_challenge_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FrbEngineStatus? sse_decode_opt_box_autoadd_frb_engine_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_frb_engine_status(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (int, bool) sse_decode_record_u_32_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_u_32(deserializer);
    var var_field1 = sse_decode_bool(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_frb_app_config(
    FrbAppConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frb_app_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_frb_challenge_info(
    FrbChallengeInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frb_challenge_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_frb_engine_config(
    FrbEngineConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frb_engine_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_frb_engine_status(
    FrbEngineStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frb_engine_status(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_frb_app_config(FrbAppConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dataDir, serializer);
    sse_encode_list_String(self.watchDirs, serializer);
    sse_encode_u_32(self.retentionDays, serializer);
    sse_encode_u_64(self.presenceChallengeIntervalSecs, serializer);
    sse_encode_u_64(self.presenceResponseWindowSecs, serializer);
    sse_encode_frb_vdf_params(self.vdfParams, serializer);
  }

  @protected
  void sse_encode_frb_challenge_info(
    FrbChallengeInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.challengeType, serializer);
    sse_encode_String(self.prompt, serializer);
    sse_encode_String(self.issuedAt, serializer);
    sse_encode_String(self.expiresAt, serializer);
    sse_encode_f_64(self.windowSecs, serializer);
  }

  @protected
  void sse_encode_frb_checkpoint_info(
    FrbCheckpointInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.ordinal, serializer);
    sse_encode_String(self.timestamp, serializer);
    sse_encode_String(self.contentHash, serializer);
    sse_encode_i_64(self.contentSize, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_bool(self.hasVdfProof, serializer);
    sse_encode_opt_box_autoadd_f_64(self.elapsedTimeSecs, serializer);
  }

  @protected
  void sse_encode_frb_engine_config(
    FrbEngineConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dataDir, serializer);
    sse_encode_list_String(self.watchDirs, serializer);
    sse_encode_u_32(self.retentionDays, serializer);
  }

  @protected
  void sse_encode_frb_engine_status(
    FrbEngineStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.running, serializer);
    sse_encode_bool(self.accessibilityTrusted, serializer);
    sse_encode_list_String(self.watchDirs, serializer);
    sse_encode_u_64(self.eventsWritten, serializer);
    sse_encode_u_64(self.jitterSamples, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastEventTimestampNs, serializer);
  }

  @protected
  void sse_encode_frb_export_result(
    FrbExportResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.outputPath, serializer);
    sse_encode_opt_String(self.packetHash, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_frb_forensic_report(
    FrbForensicReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.confidenceScore, serializer);
    sse_encode_bool(self.isAnomaly, serializer);
    sse_encode_bool(self.isRetypedContent, serializer);
    sse_encode_u_32(self.signalCount, serializer);
  }

  @protected
  void sse_encode_frb_hardware_status(
    FrbHardwareStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enclaveActive, serializer);
    sse_encode_bool(self.tpmActive, serializer);
    sse_encode_String(self.siliconId, serializer);
  }

  @protected
  void sse_encode_frb_presence_status(
    FrbPresenceStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.sessionActive, serializer);
    sse_encode_opt_String(self.sessionId, serializer);
    sse_encode_opt_String(self.startedAt, serializer);
    sse_encode_i_32(self.challengesIssued, serializer);
    sse_encode_i_32(self.challengesPassed, serializer);
    sse_encode_i_32(self.challengesFailed, serializer);
    sse_encode_i_32(self.challengesMissed, serializer);
    sse_encode_f_64(self.verificationRate, serializer);
    sse_encode_bool(self.hasPendingChallenge, serializer);
  }

  @protected
  void sse_encode_frb_report_file(
    FrbReportFile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filePath, serializer);
    sse_encode_i_64(self.lastEventTimestampNs, serializer);
    sse_encode_u_64(self.eventCount, serializer);
  }

  @protected
  void sse_encode_frb_tracking_statistics(
    FrbTrackingStatistics self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.totalKeystrokes, serializer);
    sse_encode_i_32(self.totalSamples, serializer);
    sse_encode_f_64(self.durationSecs, serializer);
    sse_encode_f_64(self.keystrokesPerMin, serializer);
    sse_encode_i_32(self.uniqueDocHashes, serializer);
    sse_encode_bool(self.chainValid, serializer);
  }

  @protected
  void sse_encode_frb_tracking_status(
    FrbTrackingStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.active, serializer);
    sse_encode_opt_String(self.sessionId, serializer);
    sse_encode_opt_String(self.documentPath, serializer);
    sse_encode_opt_String(self.startedAt, serializer);
    sse_encode_u_64(self.keystrokeCount, serializer);
    sse_encode_u_32(self.sampleCount, serializer);
    sse_encode_f_64(self.durationSecs, serializer);
  }

  @protected
  void sse_encode_frb_vdf_params(FrbVdfParams self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.iterationsPerSecond, serializer);
    sse_encode_u_64(self.minIterations, serializer);
    sse_encode_u_64(self.maxIterations, serializer);
  }

  @protected
  void sse_encode_frb_verification_result(
    FrbVerificationResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.valid, serializer);
    sse_encode_u_32(self.checkpointCount, serializer);
    sse_encode_f_64(self.totalElapsedTimeSecs, serializer);
    sse_encode_opt_String(self.firstCommit, serializer);
    sse_encode_opt_String(self.lastCommit, serializer);
    sse_encode_list_String(self.errors, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_frb_checkpoint_info(
    List<FrbCheckpointInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_frb_checkpoint_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_frb_report_file(
    List<FrbReportFile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_frb_report_file(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_frb_challenge_info(
    FrbChallengeInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_frb_challenge_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_frb_engine_status(
    FrbEngineStatus? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_frb_engine_status(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_record_u_32_bool((int, bool) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.$1, serializer);
    sse_encode_bool(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
