// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FrbAppConfig dco_decode_box_autoadd_frb_app_config(dynamic raw);

  @protected
  FrbChallengeInfo dco_decode_box_autoadd_frb_challenge_info(dynamic raw);

  @protected
  FrbEngineConfig dco_decode_box_autoadd_frb_engine_config(dynamic raw);

  @protected
  FrbEngineStatus dco_decode_box_autoadd_frb_engine_status(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FrbAppConfig dco_decode_frb_app_config(dynamic raw);

  @protected
  FrbChallengeInfo dco_decode_frb_challenge_info(dynamic raw);

  @protected
  FrbCheckpointInfo dco_decode_frb_checkpoint_info(dynamic raw);

  @protected
  FrbEngineConfig dco_decode_frb_engine_config(dynamic raw);

  @protected
  FrbEngineStatus dco_decode_frb_engine_status(dynamic raw);

  @protected
  FrbExportResult dco_decode_frb_export_result(dynamic raw);

  @protected
  FrbForensicReport dco_decode_frb_forensic_report(dynamic raw);

  @protected
  FrbHardwareStatus dco_decode_frb_hardware_status(dynamic raw);

  @protected
  FrbPresenceStatus dco_decode_frb_presence_status(dynamic raw);

  @protected
  FrbReportFile dco_decode_frb_report_file(dynamic raw);

  @protected
  FrbTrackingStatistics dco_decode_frb_tracking_statistics(dynamic raw);

  @protected
  FrbTrackingStatus dco_decode_frb_tracking_status(dynamic raw);

  @protected
  FrbVdfParams dco_decode_frb_vdf_params(dynamic raw);

  @protected
  FrbVerificationResult dco_decode_frb_verification_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FrbCheckpointInfo> dco_decode_list_frb_checkpoint_info(dynamic raw);

  @protected
  List<FrbReportFile> dco_decode_list_frb_report_file(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  FrbChallengeInfo? dco_decode_opt_box_autoadd_frb_challenge_info(dynamic raw);

  @protected
  FrbEngineStatus? dco_decode_opt_box_autoadd_frb_engine_status(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  (int, bool) dco_decode_record_u_32_bool(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FrbAppConfig sse_decode_box_autoadd_frb_app_config(
    SseDeserializer deserializer,
  );

  @protected
  FrbChallengeInfo sse_decode_box_autoadd_frb_challenge_info(
    SseDeserializer deserializer,
  );

  @protected
  FrbEngineConfig sse_decode_box_autoadd_frb_engine_config(
    SseDeserializer deserializer,
  );

  @protected
  FrbEngineStatus sse_decode_box_autoadd_frb_engine_status(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FrbAppConfig sse_decode_frb_app_config(SseDeserializer deserializer);

  @protected
  FrbChallengeInfo sse_decode_frb_challenge_info(SseDeserializer deserializer);

  @protected
  FrbCheckpointInfo sse_decode_frb_checkpoint_info(
    SseDeserializer deserializer,
  );

  @protected
  FrbEngineConfig sse_decode_frb_engine_config(SseDeserializer deserializer);

  @protected
  FrbEngineStatus sse_decode_frb_engine_status(SseDeserializer deserializer);

  @protected
  FrbExportResult sse_decode_frb_export_result(SseDeserializer deserializer);

  @protected
  FrbForensicReport sse_decode_frb_forensic_report(
    SseDeserializer deserializer,
  );

  @protected
  FrbHardwareStatus sse_decode_frb_hardware_status(
    SseDeserializer deserializer,
  );

  @protected
  FrbPresenceStatus sse_decode_frb_presence_status(
    SseDeserializer deserializer,
  );

  @protected
  FrbReportFile sse_decode_frb_report_file(SseDeserializer deserializer);

  @protected
  FrbTrackingStatistics sse_decode_frb_tracking_statistics(
    SseDeserializer deserializer,
  );

  @protected
  FrbTrackingStatus sse_decode_frb_tracking_status(
    SseDeserializer deserializer,
  );

  @protected
  FrbVdfParams sse_decode_frb_vdf_params(SseDeserializer deserializer);

  @protected
  FrbVerificationResult sse_decode_frb_verification_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FrbCheckpointInfo> sse_decode_list_frb_checkpoint_info(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbReportFile> sse_decode_list_frb_report_file(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FrbChallengeInfo? sse_decode_opt_box_autoadd_frb_challenge_info(
    SseDeserializer deserializer,
  );

  @protected
  FrbEngineStatus? sse_decode_opt_box_autoadd_frb_engine_status(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  (int, bool) sse_decode_record_u_32_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frb_app_config(
    FrbAppConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_challenge_info(
    FrbChallengeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_engine_config(
    FrbEngineConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_engine_status(
    FrbEngineStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_frb_app_config(FrbAppConfig self, SseSerializer serializer);

  @protected
  void sse_encode_frb_challenge_info(
    FrbChallengeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_checkpoint_info(
    FrbCheckpointInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_engine_config(
    FrbEngineConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_engine_status(
    FrbEngineStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_export_result(
    FrbExportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_forensic_report(
    FrbForensicReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_hardware_status(
    FrbHardwareStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_presence_status(
    FrbPresenceStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_report_file(FrbReportFile self, SseSerializer serializer);

  @protected
  void sse_encode_frb_tracking_statistics(
    FrbTrackingStatistics self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_tracking_status(
    FrbTrackingStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_vdf_params(FrbVdfParams self, SseSerializer serializer);

  @protected
  void sse_encode_frb_verification_result(
    FrbVerificationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_frb_checkpoint_info(
    List<FrbCheckpointInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_report_file(
    List<FrbReportFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_frb_challenge_info(
    FrbChallengeInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_frb_engine_status(
    FrbEngineStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_bool((int, bool) self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
